version: '3.4'
services:

  nacos1.1.3:
    hostname: nacos1-1-3
    container_name: nacos1.1.3
    image: nacos/nacos-server:1.1.3
    restart: always
    volumes:
      - /docker/nacos1.1.3/logs:/home/nacos/logs
      - /docker/nacos1.1.3/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    env_file:
      - /docker/nacos1.1.3/nacos-hostname.env