version: '3.4'
services:

  redis2.8:
    hostname: redis2-8
    container_name: redis2.8
    image: redis:2.8
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - /docker/redis2.8/config:/usr/local/etc/redis
      - /docker/redis2.8/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf