version: '3.4'
services:

  elasticsearch6.8:
    image: elasticsearch:6.8.0
    container_name: elasticsearch6.8
    hostname: elasticsearch6-8
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /docker/elasticsearch6.8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /docker/elasticsearch6.8/data:/usr/share/elasticsearch/data
      - /docker/elasticsearch6.8/logs:/usr/share/elasticsearch/logs

